### ISSUE TITLE
ライセンス

### ISSUE THREAD

**Issue by testusuke** [sya-ri/HAL_Extension#17]
このライブラリを私の方で使いたいと考えているのですが、ライセンスが指定されてないために改変してもいいのかわかりません。
GitHubの規約によれば、GitHub上での複製(forkを指している..?)は問題ないですが、改変に関して明示されていませんでした。
もしよろしければライセンスを意図的に無しにしているのか、もしくはライセンスのつけ忘れなのか教えていただきたいです。

**Comment by sya-ri** [comment]
改変して問題ないです！ライブラリの開発経験がそこまでない時に作ったものなのでライセンスのつけ忘れですね。

また、見ての通り、最近メンテナンスがされていませんが、使われてはいます。ちょうど昨日、機能の追加・修正の相談を後輩からされ、1ヶ月ほどで終わらせるとのことです。現在、C++11を想定しており使い勝手が悪いので、v7.0.0ではC++17に変更する予定です。

**Comment by testusuke** [comment]
了解しました！ありがとうございます。
